#   Main makefile
#    
#   Copyright (C) 2021 DeepLang

clean:
	rm -rf *.aux *.pdf *.log *.idx *.toc  ./*.out  ./preface/*.aux  ./postscript/*.aux ./chapter/Art/*.aux  ./chapter/Geography/*.aux   ./chapter/Technology/*.aux  ./chapter/Science/*.aux  ./chapter/Music/*.aux  ./chapter/International/*.aux ./preface/*.log
